base_app/urls.py
from django.conf.urls import url
from base_app import views

app_name = 'base_app'
urlpatterns = [
    # url(r'^login/$', views.loginView.as_view(), name = 'login'),
    # url(r'^register/$', views.RegisterView.as_view(), name = 'register'),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/main/$', views.mainpage, name = 'main'),
    url(r'^login/main/train/$', views.trainpage, name = 'train'),
    url(r'^login/main/encryptpage/$', views.encryptpage, name = 'encryptpage'),
    url(r'^login/main/testpage/$', views.testpage, name = 'testpage'),
    url(r'^login/main/decryptpage/$', views.decryptpage, name = 'decryptpage')
    # url(r'^decrypt/$', views.decryptPageView.as_view(), name = 'decrypt'),
    # url(r'^train/(?P<pk>\d+)$', views.trainImageView.as_view(), name = 'train'),

]

college_minor/urls.py
from django.conf.urls import url, include
from base_app import views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^base_app/', include('base_app.urls', namespace='base_app'))
]

base_app/models.py
from django.db import models
from django.contrib.auth.models import User

class AppUser(models.Model):
    user = models.OneToOneField(User)

    # def __str__(self):
    #     return self.user.username
   

class SecretKey(models.Model):
    user = models.ForeignKey(AppUser, unique = True)
    key = models.CharField(max_length= 32)

base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import AppUser

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

class linkform(forms.ModelForm):
    class Meta():
        model = AppUser
        fields = ()

base_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from django.views.generic import View,TemplateView
from .forms import UserForm, linkform

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth import login,logout,authenticate
import pyAesCrypt
# encryption/decryption buffer size - 64K
bufferSize = 64 * 1024
password = "foopassword"

class IndexView(TemplateView):
    template_name = 'index.html'

# class loginView(TemplateView):
#     template_name = 'login.html'

# class RegisterView(TemplateView):
#     template_name = 'register.html'

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        link_form = linkform(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            linke = link_form.save(commit = False)
            linke.user = user
            linke.save()
            registered = True
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request, 'register.html', {'user_form':user_form,'registered':registered})     



def userlogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username= username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('main')
            else:
                return HttpResponse("Account Not active")
        
        else:
            print("Well you Failed to login")

            return HttpResponse("Invalid Login Details")

    else:
        return render(request, 'login.html')


def mainpage(request):
    return render(request, 'loggedindex.html')


def trainpage(request):
    return render(request, 'trainpage.html')
    
def encryptpage(request):
    if request.method=='POST':
        uploaded_file=request.FILES['document']
        # print(uploaded_file.name)
        pyAesCrypt.encryptFile(uploaded_file.name, uploaded_file.name+".aes", password, bufferSize)
        # pyAesCrypt.decryptFile("data.txt.aes", "dataout.txt", password, bufferSize)

    return render(request, 'encryptpage.html')

def testpage(request):
    return render(request, 'testpage.html')

def decryptpage(request):
    if request.method=='POST':
        uploaded_file=request.FILES['document']
        # print(uploaded_file.name)
        pyAesCrypt.decryptFile(uploaded_file.name, "dataout.txt", password, bufferSize)

    return render(request, 'decryptpage.html')

# class LoggedIndexView(TemplateView):
#     template_name = 'loggedindex.html'

# class decryptPageView(TemplateView):
#     template_name = 'decryptpage.html'

# class trainImageView(TemplateView):
#     template_name = 'train.html'

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {%block title_block %} {% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar  navbar-dark bg-dark" style="min-height: 30px; font-family: Andale Mono, monospace;" >
      <div class="container-fluid">
        <div class= "navbar-header">
          <a href="http://127.0.0.1:8000/" class="navbar-brand" href="#" style=" padding: 0 15px;height: 30px;line-height: 30px;">BioCrypt</a>
        </div>
      </div>
    </nav>
    <div class="container " style="width:100%; margin-top: 10px">

      {% block body_block %}
      {% endblock %}

    </div>
  <br><br>
    <footer class="text-muted text-center" style="font-size: x-small; position: relative; bottom: 0;width: 100%;">   <!--  change -->
        <div class="container">
          <p>BioCrypt is a &copy; XYZ, Made for the purpose of being presented as 7th Sem minor project DTU</p>
          <p>New to BioCrypt? <a href="#">Visit the about section</a> or read our <a href="#">getting started guide</a>.</p>
        </div>
    </footer>
  </body>
</html>

templates/decryptpage.html
{% extends "base.html"%}
{%block title_block %}<title>Decrypt</title>{% endblock %}
{% block body_block %}
	<h2>Upload the file to decrypt</h2>
	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<input type="file" name="document">
		<button type="submit">Upload File</button>
	</form>
{% endblock %}

templates/encryptpage.html
{% extends "base.html"%}
{%block title_block %}<title>Encrypt</title>{% endblock %}
{% block body_block %}
	<h2>Upload the file to encrypt</h2>
	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<input type="file" name="document">
		<button type="submit">Upload File</button>
	</form>
{% endblock %}

templates/index.html
{% extends "base.html"%}
{%block title_block %}<title>BioCrypt</title>{% endblock %}
{% block body_block %}
    <div class="jumbotron text-center">
        <div class="container" >
            <div class="row">
                <div class="col-lg-12">
                    <h1>Welcome To BioCrypt</h1>
                    <p>Please Log-in to Encrypt and Decrypt your Files</p>
                    <a href="{% url 'base_app:login' %}" class="btn btn-outline-primary btn-sm active" role="button" aria-pressed="true">Log In</a>
                    <a href="{% url 'base_app:register' %}" class="btn btn-dark btn-sm active" role="button" aria-pressed="true">Register</a>
                </div>
            </div>
        </div>
    </div>
  <div class="container">
  <br><br>
  <div class="row">
    <div class="col-sm-4" style="">
      <p style="font-weight: bold;">About us</p>
      <div style="font-size: 80%;">
      Face recognition has been employed in various security-related applications such as surveillance, mugshot identi-ﬁcation, e-passport, and access control. Despite its recentadvancements, privacy concern is one of several issues pre-venting its wider deployment. In this paper, we address theprivacy concern for a self-exclusion scenario of face recognition. 
      </div>
    </div>
    <div class="col-sm-4" style="padding-left: 70px;">
      <p style="font-weight: bold;">How it works?</p>
      <ul>
        <li>
          <a href="">Face recognition</a>
        </li>
        <li>
          <a href="">Encryption</a>
        </li>
        <li>
          <a href="">Decryption</a>
        </li>
      </ul>
    </div>
    <div class="col-sm-4">
      <p style="font-weight: bold; text-align: left;">Contacts</p>
      <ul>
        <li>
          <a href="">sales@kairos.com</a>
        </li>
        <li>
          <a href="">support@kairos.com</a>
        </li>
        <li>
          <a href="">press@kairos.com</a>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/loggedindex.html
{% extends "base.html"%}

{%block title_block %}<title>BioCrypt</title>{% endblock %}
{% block body_block %}
    <div class="jumbotron text-center">
        <div class="container" >
            <div class="row">
                <div class="col-lg-12">
                    <h1>Welcome To BioCrypt</h1>
                    <p>Here you are</p>
                    <a href="{% url 'base_app:encryptpage' %}" class="btn btn-outline-primary btn-sm active" role="button" aria-pressed="true">Encrypt</a>
                    <a href="{% url 'base_app:testpage' %}" class="btn btn-dark btn-sm active" role="button" aria-pressed="true">Decrypt</a>
                    <a href="{% url 'base_app:train' %}" class="btn btn-light btn-sm active" role="button" aria-pressed="true">Train</a>

                </div>
            </div>
        </div>
    </div>
    <div class="container">
  <br><br>
  <div class="row">
    <div class="col-sm-4" style="">
      <p style="font-weight: bold;">About us</p>
      <div style="font-size: 80%;">
      Face recognition has been employed in various security-related applications such as surveillance, mugshot identi-ﬁcation, e-passport, and access control. Despite its recentadvancements, privacy concern is one of several issues pre-venting its wider deployment. In this paper, we address theprivacy concern for a self-exclusion scenario of face recognition. 
      </div>
    </div>
    <div class="col-sm-4" style="padding-left: 70px;">
      <p style="font-weight: bold;">How it works?</p>
      <ul>
        <li>
          <a href="">Face recognition</a>
        </li>
        <li>
          <a href="">Encryption</a>
        </li>
        <li>
          <a href="">Decryption</a>
        </li>
      </ul>
    </div>
    <div class="col-sm-4">
      <p style="font-weight: bold; text-align: left;">Contacts</p>
      <ul>
        <li>
          <a href="">sales@kairos.com</a>
        </li>
        <li>
          <a href="">support@kairos.com</a>
        </li>
        <li>
          <a href="">press@kairos.com</a>
        </li>
      </ul>
    </div>
  </div>
</div>
    {% endblock %}

templates/login.html
{% extends "base.html"%}
{%block title_block %}<title>BioCrypt Login</title>{% endblock %}
{% block body_block %}
<div class="container" style="width:70%">
    <div class="jumbotron text-center">
        <h3>Login Here</h3>
        <form action="" method="post">
            {% csrf_token %}
            
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            
            <label for="password">Password:</label>
            <input type="password" name="password" >
            
            <input type="Submit" value="Login" class="btn btn-default">
        
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html"%}
{%block title_block %}<title>Register</title>{% endblock %}
{% block body_block %}
<div class="container" style="width:80%">
    <div class="jumbotron text-center" style="padding-left:80px;padding-right:80px;">
        {% if registered %}
            <h3>Thank You for registering</h3>
            <p>Please<a href="{%url 'base_app:login'%}">Login</a> with your credentials</p>
        {% else %}
            <h3 >Please Sign Up Here</h3>
          
            <form class = "" action="" method="post">
                {% csrf_token %}
                {{ user_form.as_p}}
                {{ link_form.as_p}}
                <input type="submit" name="" value="Register" class="btn btn-default">
           
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/testpage.html
{% extends "base.html"%}
{%block title_block %}<title>Decrypt</title>{% endblock %}
{% block body_block %}
	
  <body onload="init();">
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     {% load staticfiles %}
  <script src="{% static "js/materialize.min.js" %}"></script>
      
      <div class="container">
            <div class="card center">
 
                    <div class="card-content">
                            <div class="card-action">
                               <button class="btn btn-default " onclick="startWebcam();" style="margin-bottom: 5px; margin-top: 5px; width: 100px">Camera On</button>
                        <button class="btn btn-default" onclick="snapshot();" style="margin-bottom: 5px; margin-top: 5px;width: 100px">Verify</button>
                            </div>
                           <!--  <div class="input-field col s6">
                                    <input placeholder="Enter user id" type="text" class="validate" id="ip">
                            </div> -->
                            <p>
                                <video onclick="snapshot(this);" width=300 height=300 id="video" controls autoplay></video>
                                <br>
                                <canvas  id="myCanvas" width="300" height="220"></canvas>
                            </p>
                    </div>
                   <!--  <audio id="myAudio">
                            <source src="success.wav" type="audio/wav">
                    </audio> -->

                  </div>
      </div>
  </body>
  <script type="text/javascript">
    //--------------------
    // GET USER MEDIA CODE
    //--------------------
        navigator.getUserMedia = ( navigator.getUserMedia ||
                           navigator.webkitGetUserMedia ||
                           navigator.mozGetUserMedia ||
                           navigator.msGetUserMedia);
    var video;
    var webcamStream;
    function startWebcam() {
      if (navigator.getUserMedia) {
         navigator.getUserMedia (
            // constraints
            {
               video: true,
               audio: false
            },
            // successCallback
            function(localMediaStream) {
                video = document.querySelector('video');
               video.src = window.URL.createObjectURL(localMediaStream);
               webcamStream = localMediaStream;
            },
            // errorCallback
            function(err) {
               console.log("The following error occured: " + err);
            }
         );
      } else {
         console.log("getUserMedia not supported");
      }  
    }
    //---------------------
    // TAKE A SNAPSHOT CODE
    //---------------------
    var canvas, ctx;
    function init() {
      // Get the canvas and obtain a context for
      // drawing in it
      canvas = document.getElementById("myCanvas");
      ctx = canvas.getContext('2d');
    }
    function snapshot() {
        ctx.drawImage(video, 0,0, canvas.width, canvas.height);
        var img1 = new Image();
        img1.src = canvas.toDataURL();
        // var ip = document.getElementById('ip').value;
        // var x = document.getElementById("myAudio"); 
        // x.play(); 
        datad = "{\r\n    \"image\":\"" + img1.src+ "\",\r\n    \"gallery_name\":\"Arti\"\r\n}"
        var settings = {
            "async": true,
            "crossDomain": true,
            "url": "https://api.kairos.com/recognize",
            "method": "POST",
            "headers": {
                "content-type": "application/json",
                "app_id": "fee603f3",
                "app_key": "d43e26b5a87fae423d09851f347871b4",
                "cache-control": "no-cache"
            },
            "processData": false,
            "data": datad
        }
        $.ajax(settings).done(function (response) {
            var m = response;
            console.log(JSON.stringify(m).indexOf("success"));
            if(JSON.stringify(m).indexOf("success") > -1) {
                Materialize.toast('User Identfied. Name : ' +JSON.stringify(m.images[0].candidates[0].subject_id), 6000);
                console.log(m.images[0].candidates[0].subject_id);
                 window.alert("User matched");
                 window.location.href = 'http://127.0.0.1:8000/base_app/login/main/decryptpage/';
            }
            else{
                Materialize.toast('User Not identified');
                window.alert("User doesn't matches");
    			window.location.href = 'http://127.0.0.1:8000/base_app/login/main/';
            }
        });
    }
</script>
{% endblock %}

templates/trainpage.html
{% extends "base.html" %}
{% block "title_block"%} 
<title>Train</title>
{% endblock%}


{% block body_block %}
<body onload="init();">
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    {% load staticfiles %}
  <script src="{% static "js/materialize.min.js" %}"></script>
      
      <div class="container">
            <div class="card center" style="padding-left: 340px;">
 
                    <div class="card-content">
                              <div class="card-action">
                        <button class="btn btn-default " onclick="startWebcam();" style="margin-bottom: 5px; margin-top: 5px; width: 100px">Camera</button>
                        <button class="btn btn-default" onclick="snapshot();" style="margin-bottom: 5px; margin-top: 5px;width: 100px">Train  </button>
                    </div><br><br>
                            <div class="input-field col s6">
                                    <input placeholder="Enter Name" type="text" class="validate" id="ip">
                            </div>
                            <br><br>
                            <p>
                                <video onclick="snapshot(this);" width=300 height=300 id="video" controls autoplay></video>
                                <br>
                                <canvas  id="myCanvas" width="300" height="220"></canvas>
                            </p>
                    </div>

                  </div>
      </div>
  </body>
  <script type="text/javascript">
    //--------------------
    // GET USER MEDIA CODE
    //--------------------
        navigator.getUserMedia = ( navigator.getUserMedia ||
                           navigator.webkitGetUserMedia ||
                           navigator.mozGetUserMedia ||
                           navigator.msGetUserMedia);
    var video;
    var webcamStream;
    function startWebcam() {
      if (navigator.getUserMedia) {
         navigator.getUserMedia (
            // constraints
            {
               video: true,
               audio: false
            },
            // successCallback
            function(localMediaStream) {
                video = document.querySelector('video');
               video.src = window.URL.createObjectURL(localMediaStream);
               webcamStream = localMediaStream;
            },
            // errorCallback
            function(err) {
               console.log("The following error occured: " + err);
            }
         );
      } else {
         console.log("getUserMedia not supported");
      }  
    }
    //---------------------
    // TAKE A SNAPSHOT CODE
    //---------------------
    var canvas, ctx;
    function init() {
      // Get the canvas and obtain a context for
      // drawing in it
      canvas = document.getElementById("myCanvas");
      ctx = canvas.getContext('2d');
    }
    function snapshot() {
      
      ctx.drawImage(video, 0,0, canvas.width, canvas.height);
      var img1 = new Image();
      img1.src = canvas.toDataURL();
      var ip = document.getElementById('ip').value;
      datad = "{\r\n    \"image\":\"" + img1.src+ "\",\r\n    \"subject_id\":\"" + ip + "\",\r\n    \"gallery_name\":\"Arti\"\r\n}";
      var settings = {
          "async": true,
          "crossDomain": true,
          "url": "https://api.kairos.com/enroll",
          "method": "POST",
          "headers": {
              "content-type": "application/json",
              "app_id": "fee603f3",
              "app_key": "d43e26b5a87fae423d09851f347871b4",
              "cache-control": "no-cache"
          },
          "processData": false,
          "data": datad
      }
      $.ajax(settings).done(function (response) {
        //
        if((response.images[0].transaction.status) == "success"){
            Materialize.toast("Image Trained succesfully by name " +response.images[0].transaction.subject_id+ " in gallery name " +response.images[0].transaction.gallery_name, 4000);
            console.log(response.images[0].transaction.subject_id);
            window.alert("Trained succesfully");
            window.location.href = 'http://127.0.0.1:8000/base_app/login/main/';
        }
        else{
            Materialize.toast("Unable to Train Image", 4000);
            window.alert("Error");
            window.location.href = 'http://127.0.0.1:8000/base_app/login/main/';
        }
      });
      //console.log(img1.src);
    }
</script>
{% endblock %}